---
 - name: Playbook to find Python version
   hosts: {{targets}}
   gather_facts: false
   tasks:
    - name: Excutong phthonversion command using command module
      ansible.builtin.command:
        cmd: 'python --version'
      register: pythonVersion
    - name: Displaying python version using debug module
      ansible.builtin.debug:
       msg:
        - "pythonVersion is: {{pythonVersion.stdout}}"

# to run the playbook :- ansible-playbook findpythonversion.yml -e "targets=dev"
#                        - ansible-playbook findpythonversion.yml -e "targets=localhost"
#                        - ansible-playbook findpythonversion.yml -e "targets=64.203.170.125"
#                        - ansible-playbook findpythonversion.yml -e "targets=all"