---
 - name: Play to display inventory_hostname and hostvars
   hosts: 64.203.170.125,18.213.13.142
   gather_facts: false
   tasks:
    - name: Display inventory_hostname 
      ansible.builtin.debug:
        # msg: "{{inventory_hostname}}" 
        # msg: "{{hostvars[inventory_hostname]}}" 
        msg: "{{hostvars[inventory_hostname].group_names}}"