---
 - name: Setting JAVA_HOME
   hosts: dev
   gather_facts: false
   become: true
   tasks:
     - name: Downloading required tar.gz file
       ansible.builtin.get_url:
         url: https://download.java.net/java/GA/jdk18.0.2/f6ad4b4450fd4d298113270ec84f30ee/9/GPL/openjdk-18.0.2_linux-x64_bin.tar.gz
         dest: /opt/openjdk-18.0.2_linux-x64_bin.tar.gz
       delegate_to: localhost
       run_once: true
     - name: Extacing tar.gz file
       ansible.builtin.unarchive:
         src: /opt/openjdk-18.0.2_linux-x64_bin.tar.gz
         dest: /opt 
     - name: Setting JAVA_HOME variable
       ansible.builtin.lineinfile:
         path: /etc/environment
         line: "export JAVA_HOME=/opt/jdk-18.0.2"
         state: present

    #  - name: Downloading required tar.gz file
    #    ansible.builtin.get_url:
    #      url: https://download.java.net/java/GA/jdk18.0.2/f6ad4b4450fd4d298113270ec84f30ee/9/GPL/openjdk-18.0.2_linux-x64_bin.tar.gz
    #      dest: /opt/openjdk-18.0.2_linux-x64_bin.tar.gz
    #  - name: Extacing tar.gz file
    #    ansible.builtin.unarchive:
    #      src: /opt/openjdk-18.0.2_linux-x64_bin.tar.gz
    #      dest: /opt 
    #      remote_src: true
    #  - name: Setting JAVA_HOME variable
    #    ansible.builtin.lineinfile:
    #      path: /etc/environment
    #      line: "export JAVA_HOME=/opt/jdk-18.0.2"
    #      state: present


# ansible dev -m ansible.buitin.command -a 'ls -lrt /opt'  , to konw the extracted directory
# sudo rm -rf /opt/openjdk-18.0.2_linux-x64_bin.tar.gz  , from your localhost
# ansible dev -m ansible.builtin.shell -a 'rm -rf /opt/*' -b 
