---
 - hosts: localhost
   vars:
     mylist: [4,5,6,8,2]
     mynewlist: [1,3] 
     mergedlist: {{mylist + mynewlist}}
   gather_facts: false
   tasks:
     - ansible.builtin.debug:
          msg:
           - "mylist is : {{mylist}}"
           - "no of elements : {{mylist | length}}"
           - "min num : {{mylist | min}}"
           - "max num : {{mylist | max}}"
           - "first num : {{mylist[0]}}"
           - "second num : {{mylist[1]}}"
           - "first num : {{mylist[-5]}}"
           - "last num : {{mylist[-1]}}"
           - "first num with filter : {{mylist | first}}"
           - "last num with filter : {{mylist | last}}"
           - "mergedlist is : {{mergedlist}}"
     - ansible.builtin.set_fact:
         mergedlist: {{mylist + mynewlist}}
         joineddata: {{mylist | join}}
         joineddata1: {{mylist | join('-')}}
     - ansible.builtin.debug:
          - msg:
             - "joineddata1 : {{joineddata1}}"  
