---
 - hosts: localhost
   vars:
     x: 40
     my_name: 'gargi'
     my_path: '/workspaces/ansible/ansibleconcepts/ansibleoperators/testoperators.yml'
     my_link_path: '/workspaces/ansible/ansibleconcepts/ansibleoperators'
   gather_facts: false
   tasks:
     - ansible.builtin.debug:
          msg:
           - "x is defined : {{ x is defined }}"
           - "y is defined : {{ y is defined }}"
           - "z is undfined : {{ z is undefined }}"
           - "my_name is lower : {{ my_name is lower }}"
           - "my_name is upper : {{ my_name is upper }}"
           - "my_name is string : {{ my_name is string }}"
           - "x is divisibleby 2 : {{ x is divisibleby 2 }}"
           - "x is even : {{ x is even }}"
           - "x is odd : {{ x is odd }}"
           - "x is number : {{ x is number }}"
           - "the given path is : {{my_path}}"
           - "my_path is file : {{my_path is file}}"
           - "my_path is directory : {{my_path is directory}}"
           - "my_path is exists : {{my_path is exists}}"
           - "my_link_path is link : {{my_link_path is link}}"
           - "hello is lower : {{'hello' is lower}}"